class CannotAttachSharedMemory(Exception): ...

class CannotAcquireLock(Exception):
    def __init__(
        self, *args, blocking_pid: int = 0, timestamp: float | None = None, **kwargs
    ) -> None: ...

class CannotAcquireLockTimeout(CannotAcquireLock):
    def __init__(self, *args, time_passed: float | None = None, **kwargs) -> None: ...

class ParameterMismatch(Exception): ...
class AlreadyClosed(Exception): ...
class AlreadyExists(Exception): ...
class FullDumpMemoryFull(Exception): ...
class MissingDependency(Exception): ...
